### ISSUE TITLE
m2e2_annotation

### ISSUE THREAD

**Issue by CaoBourne** [limanling/m2e2#1]
I have been reading your manufacture recently and would like to run your code, but I found that the correct link to m2e2_annotation is missing in the data module. Could you provide proper access to the system code?

**Comment by a670531899** [comment]
I met this problem too, have you get this dataset now?

**Comment by limanling** [comment]
Sorry that I just notice the data link should end with `zip` instead of `tgz`. I updated the README using the correct link.

**Comment by CaoJonas** [comment]
Thank you for your reply.
