### ISSUE TITLE
Multimedia event mention and multimidia evaluation

### ISSUE THREAD

**Issue by Raising-hrx** [limanling/m2e2#7]
Hi! I have download the M2E2 raw data and annotations from the links given in README.
However, I have no idea how to find the 309 cross-media event mention pairs and 395 multimedia event mentions from the annotations, could you please show me how can I get these multimedia data?

In addition, I note that your [evaluation code](https://github.com/limanling/m2e2/blob/master/src/engine/TestRunnerJOINT.py#L563-L588) only print the text-only and image-only evaluation. Could you tell me where the code corresponding to "Multimedia Evaluation" is?

**Comment by jianliu-ml** [comment]
Hi, have you found it?

**Comment by zhanghuiecho** [comment]
Did you solve this problem? I encountered the same issue as you.

**Comment by pbz123** [comment]
I encountered the same issue as you too. Did you solve this problem?

**Comment by York-Gold** [comment]
I encountered the same issue as you too. Did you solve this problem?
